#!/bin/bash
touch sysinfo
hostname=$(hostname)
cpu=$(lscpu | grep 'CPU(s)' -m 1)
memory=$(dmidecode --type memory | grep 'Maximum Capacity' -m 1) 
total=$(cat /proc/meminfo | grep 'MemTotal')
printf "Hostname: $hostname\n$cpu\n$memory\n$total\n" > sysinfo 
